Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "sensu-enterprise-sandbox"
  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 2
    vb.memory = 4096
  end
  config.vm.network "forwarded_port", guest: 6379, host: 6379
  config.vm.network "forwarded_port", guest: 4567, host: 4567
  config.vm.network "forwarded_port", guest: 3000, host: 3000
  config.vm.network "forwarded_port", guest: 4000, host: 4000
  config.vm.provision "shell",
    env: {
      "SE_USER" => ENV["SE_USER"],
      "SE_PASS" => ENV["SE_PASS"]
    },
    path: "setup.sh"
end
